### ISSUE TITLE
Compilable output

### ISSUE THREAD

**Issue by finanalyst** [briandfoy/perl6-PrettyDump#10]
If a structure made humanly readable with this module is saved to disk, it cannot be compiled with, eg. `my $structure = EVALFILE 'PrettyDumpedData`

This can be overcome - I think - by calling four handles Array,LIst,Match,Hash so that `:start` and `:end` match Raku syntax. 

It would be nice if this was available in the Module as an option, eg. `:compilable`

**Comment by briandfoy** [comment]
I'm closing this as a duplicate of #11.
