### ISSUE TITLE
Use Data::Printer as a perl5 reference module

### ISSUE THREAD

**Issue by heikkil** [briandfoy/perl6-PrettyDump#4]
Thank you for your article http://perltricks.com/article/pretty-printing-perl-6/

You mention looking into Data::Dumper for insights but not refer to Data::Printer that in my work flow have completely replaced it. I consider it to be the best perl5 module to explore data structures. Maybe there are useful pointers for further development of PrettyDump in it.

One especially appealing feature of Data::Printer is the use of one stop print function with the shortest possible name 'p'.

**Comment by briandfoy** [comment]
What other features do you like?
